name: timesmedlite
description: Timesmed Product

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pdfx: 2.7.0
  document_file_save_plus: ^2.0.0
  auto_size_text: ^3.0.0
  timelines: ^0.1.0
  #networking
#  connectivity_plus: ^6.0.2

  cached_network_image: ^3.2.0

  #firebase
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  cloud_firestore: ^4.2.0

  #firebase_message_handling
  firebase_notifications_handler: ^1.1.0

  #uiorder
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.1.1
  pinput: ^4.0.0
  flutter_svg: ^1.1.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  table_calendar: ^3.0.3
  #  cross_connectivity: ^3.2.0
  shimmer: ^2.0.0
  flutter_portal: ^1.1.1
  flutter_rating_bar: ^4.0.1
  circular_countdown_timer: ^0.2.3
  pdf: ^3.11.1
  printing: ^5.9.3
  map: ^1.3.5+1
  fl_chart: ^0.69.0

  dart_jsonwebtoken: ^2.14.1

  #itl
  barcode_widget: ^2.0.2
  cc_avenue:
    path: ./cc_avenue
  #  opentok_flutter:
  #    path: ./opentok_flutter
  #flutter_vonage_video: 0.0.3
  #knovi_call: ^0.0.1
  #opentok_flutter: ^0.0.1


  intl: 0.17.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  file_picker: ^5.2.3
  path_provider: ^2.0.11
  dio: ^4.0.6
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6
  razorpay_flutter: ^1.3.4
  loading_indicator: ^3.1.0
  #flutter_chips_input: ^2.0.0
  transparent_image: ^2.0.0
  age_calculator: ^1.0.0
  geolocator: ^9.0.2
  advance_pdf_viewer2: 2.0.5
  pdf_widget_wrapper: ^1.0.4
  socket_io_client: ^2.0.2
  hexcolor: ^3.0.1
  flutter_webrtc: ^0.11.6+hotfix.1
  livekit_client: ^2.2.4



dependency_overrides:
  freezed_annotation: ^2.0.3
  permission_handler: ^10.2.0
  connectivity_plus: ^6.0.5
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.13
  chopper_generator: ^8.0.1
  freezed: ^2.5.7
  json_serializable: ^6.2.0
  lint: ^1.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/sounds/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages