// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:timesmedlite/ui/app/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform(Config config) {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if(config == Config.doctor) {
          return androidDoctor;
        } else {
          return androidPatient;
        }
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIeZqV3D4OxHpKzcH_JXFi7hqvfTyaEqw',
    appId: '1:591329525692:web:d47149d06390915da875b9',
    messagingSenderId: '591329525692',
    projectId: 'timesmed-new-patient',
    authDomain: 'timesmed-new-patient.firebaseapp.com',
    storageBucket: 'timesmed-new-patient.appspot.com',
    measurementId: 'G-C9Z83X8QRF',
  );

  static const FirebaseOptions androidDoctor = FirebaseOptions(
    apiKey: 'AIzaSyCr8JRq6imHrK1NGoJvfmydPBHn-t2Q-6Q',
    appId: '1:591329525692:android:11a4c979841e2a36a875b9',
    messagingSenderId: '591329525692',
    projectId: 'timesmed-new-patient',
    storageBucket: 'timesmed-new-patient.appspot.com',
  );
  static const FirebaseOptions androidPatient = FirebaseOptions(
    apiKey: 'AIzaSyCr8JRq6imHrK1NGoJvfmydPBHn-t2Q-6Q',
    appId: '1:591329525692:android:fee11ededfd38b75a875b9',
    messagingSenderId: '591329525692',
    projectId: 'timesmed-new-patient',
    storageBucket: 'timesmed-new-patient.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmSnx93U7Trl_mECcaBGlMTVvidvzgfTU',
    appId: '1:591329525692:ios:3d25b93943ffb6fda875b9',
    messagingSenderId: '591329525692',
    projectId: 'timesmed-new-patient',
    storageBucket: 'timesmed-new-patient.appspot.com',
    iosClientId: '591329525692-gragufbnua1jajdm4oj1c6m9mbstd0la.apps.googleusercontent.com',
    iosBundleId: 'com.finservtech.timesmedlite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmSnx93U7Trl_mECcaBGlMTVvidvzgfTU',
    appId: '1:591329525692:ios:3d25b93943ffb6fda875b9',
    messagingSenderId: '591329525692',
    projectId: 'timesmed-new-patient',
    storageBucket: 'timesmed-new-patient.appspot.com',
    iosClientId: '591329525692-gragufbnua1jajdm4oj1c6m9mbstd0la.apps.googleusercontent.com',
    iosBundleId: 'com.finservtech.timesmedlite',
  );
}
