// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'clinic.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Clinic _$$_ClinicFromJson(Map<String, dynamic> json) => _$_Clinic(
      Location_Name_Temp: json['Location_Name_Temp'] ?? '',
      URL_String: json['URL_String'] ?? '',
      Clinic_NameTemp: json['Clinic_NameTemp'] ?? '',
      Type_Flag: json['Type_Flag'] ?? '',
      Clinic_id: json['Clinic_id'] ?? '',
      Clinic_Name: json['Clinic_Name'] ?? '',
      Clinic_Name_temp: json['Clinic_Name_temp'] ?? '',
      Clinic_Address: json['Clinic_Address'] ?? '',
      SubCategory_id: json['SubCategory_id'] ?? '',
      Location_id: json['Location_id'] ?? '',
      Location_name: json['Location_name'] ?? '',
      ClinicDoctorFee: json['ClinicDoctorFee'] ?? '',
      FromTime: json['FromTime'] ?? '',
      FeedBack: json['FeedBack'] ?? '',
      Doctor_id: json['Doctor_id'] ?? '',
      startSplit: json['startSplit'] ?? '',
      EndSplit: json['EndSplit'] ?? '',
      ToTime: json['ToTime'] ?? '',
      Day: json['Day'] ?? '',
      AboutClinic: json['AboutClinic'] ?? '',
      Clinic_Images: json['Clinic_Images'] ?? '',
      CandHList: json['CandHList'] ?? '',
      Location_Name: json['Location_Name'] ?? '',
      Days: json['Days'] ?? '',
      SubCategory_Name: json['SubCategory_Name'] ?? '',
      Class: json['Class'] ?? '',
      Link: json['Link'] ?? '',
      Banner_Id: json['Banner_Id'] ?? '',
      Banner_Image: json['Banner_Image'] ?? '',
      listbanner: json['listbanner'] ?? '',
      Timing: json['Timing'] ?? '',
      PhoneNumber: json['PhoneNumber'] ?? '',
      SerList: json['SerList'] ?? '',
      SubCategoryList: json['SubCategoryList'] ?? '',
      CImage: json['CImage'] ?? '',
      LocationList: json['LocationList'] ?? '',
      Count: json['Count'] ?? '',
      count: json['count'] ?? '',
      Lat: json['Lat'] ?? '',
      longi: json['longi'] ?? '',
      Hospital_Speciliazation: json['Hospital_Speciliazation'] ?? '',
      Hospital_Type: json['Hospital_Type'] ?? '',
      Hospital_Address: json['Hospital_Address'] ?? '',
      Currency: json['Currency'] ?? '',
      City_Name: json['City_Name'] ?? '',
      Country_Name: json['Country_Name'] ?? '',
      Hospital_URL_With_Name: json['Hospital_URL_With_Name'] ?? '',
      HospitalDetails_id: json['HospitalDetails_id'] ?? '',
      user_id: json['user_id'] ?? '',
      user_name: json['user_name'] ?? '',
      user_image: json['user_image'] ?? '',
      mobileno: json['mobileno'] ?? '',
      app_id: json['app_id'] ?? '',
      view_flag: json['view_flag'] ?? '',
      daySlot: (json['DaySlot'] as List<dynamic>?)
          ?.map((e) => DaySlot.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$$_ClinicToJson(_$_Clinic instance) => <String, dynamic>{
      'Location_Name_Temp': instance.Location_Name_Temp,
      'URL_String': instance.URL_String,
      'Clinic_NameTemp': instance.Clinic_NameTemp,
      'Type_Flag': instance.Type_Flag,
      'Clinic_id': instance.Clinic_id,
      'Clinic_Name': instance.Clinic_Name,
      'Clinic_Name_temp': instance.Clinic_Name_temp,
      'Clinic_Address': instance.Clinic_Address,
      'SubCategory_id': instance.SubCategory_id,
      'Location_id': instance.Location_id,
      'Location_name': instance.Location_name,
      'ClinicDoctorFee': instance.ClinicDoctorFee,
      'FromTime': instance.FromTime,
      'FeedBack': instance.FeedBack,
      'Doctor_id': instance.Doctor_id,
      'startSplit': instance.startSplit,
      'EndSplit': instance.EndSplit,
      'ToTime': instance.ToTime,
      'Day': instance.Day,
      'AboutClinic': instance.AboutClinic,
      'Clinic_Images': instance.Clinic_Images,
      'CandHList': instance.CandHList,
      'Location_Name': instance.Location_Name,
      'Days': instance.Days,
      'SubCategory_Name': instance.SubCategory_Name,
      'Class': instance.Class,
      'Link': instance.Link,
      'Banner_Id': instance.Banner_Id,
      'Banner_Image': instance.Banner_Image,
      'listbanner': instance.listbanner,
      'Timing': instance.Timing,
      'PhoneNumber': instance.PhoneNumber,
      'SerList': instance.SerList,
      'SubCategoryList': instance.SubCategoryList,
      'CImage': instance.CImage,
      'LocationList': instance.LocationList,
      'Count': instance.Count,
      'count': instance.count,
      'Lat': instance.Lat,
      'longi': instance.longi,
      'Hospital_Speciliazation': instance.Hospital_Speciliazation,
      'Hospital_Type': instance.Hospital_Type,
      'Hospital_Address': instance.Hospital_Address,
      'Currency': instance.Currency,
      'City_Name': instance.City_Name,
      'Country_Name': instance.Country_Name,
      'Hospital_URL_With_Name': instance.Hospital_URL_With_Name,
      'HospitalDetails_id': instance.HospitalDetails_id,
      'user_id': instance.user_id,
      'user_name': instance.user_name,
      'user_image': instance.user_image,
      'mobileno': instance.mobileno,
      'app_id': instance.app_id,
      'view_flag': instance.view_flag,
      'DaySlot': instance.daySlot,
    };
