// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'get_doctor_details.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$GetDoctorDetailsImpl _$$GetDoctorDetailsImplFromJson(
        Map<String, dynamic> json) =>
    _$GetDoctorDetailsImpl(
      prcNumber: json['PRC_Number'] as String?,
      cityId: (json['City_Id'] as num?)?.toInt(),
      cityName: json['City_Name'] ?? null,
      languageName: json['Language_Name'] ?? null,
      languageId: json['Language_Id'] ?? null,
      middleName: json['Middle_Name'] as String?,
      lastName: json['Last_Name'] as String?,
      url: json['URL'] ?? null,
      virtual: json['Virtual'] ?? null,
      service: json['Service'] ?? null,
      online: json['Online'] as String?,
      accountName: json['AccountName'] as String?,
      bankName: json['BankName'] as String?,
      accountNo: json['AccountNo'] as String?,
      branchName: json['BranchName'] as String?,
      ifscCode: json['IFSCCode'] as String?,
      hospitalId: (json['Hospital_id'] as num?)?.toInt(),
      hospitalName: json['Hospital_Name'] ?? null,
      password: json['Password'] as String?,
      lat: (json['Lat'] as num?)?.toInt() ?? null,
      doctorCategoryId: (json['DoctorCategory_id'] as num?)?.toInt(),
      doctorCategoryName: json['DoctorCategory_Name'] as String?,
      file: json['file'] ?? null,
      long: (json['Long'] as num?)?.toInt(),
      locationName: json['Location_Name'] ?? null,
      category: json['Category'] ?? null,
      doctorId: (json['Doctor_id'] as num?)?.toInt(),
      doctorName: json['Doctor_Name'] as String?,
      qualificationName: json['QualificationName'] ?? null,
      doctorQualification: json['Doctor_Qualification'] as String?,
      locationId: (json['Location_id'] as num?)?.toInt(),
      subCategoryId: json['SubCategory_id'] as String?,
      doctorExperienceYears: (json['DoctorExperience_Years'] as num?)?.toInt(),
      recommendations: (json['Recommendations'] as num?)?.toInt(),
      doctorDescription: json['Doctor_Description'] as String?,
      doctorImage: json['Doctor_Image'] as String?,
      doctorAge: (json['Doctor_Age'] as num?)?.toInt(),
      doctorPhoneNumber: json['Doctor_PhoneNumber'] as String?,
      subCategoryName: json['SubCategory_Name'] ?? null,
      doctorAddress: json['Doctor_Address'] as String?,
      clinicDoctorFee: (json['ClinicDoctorFee'] as num?)?.toInt(),
      typeFlag: json['Type_Flag'] ?? null,
      days: json['Days'] ?? null,
      sscategoryName: json['sscategory_Name'] ?? null,
      sscatId: (json['sscat_id'] as num?)?.toInt(),
      emailId: json['Email_id'] as String?,
      subCat: json['SubCat'] ?? null,
      gender: json['Gender'] as String?,
      status: (json['Status'] as num?)?.toInt(),
      flag: json['Flag'] ?? null,
      doctorMobileCountrycode: json['Doctor_Mobile_countrycode'] as String?,
      doctorQualificationCode: json['Doctor_QualificationCode'] ?? null,
      doctorDob: json['Doctor_DOB'] as String?,
      doctorList: json['Doctor_List'] ?? null,
      cityList: json['City_List'] ?? null,
      langList: json['Langugage_List'] ?? null,
      docList: json['Doclist'] ?? null,
      qualificationList: json['QualificationList'] ?? null,
      categoryList: json['CategoryList'] ?? null,
    );

Map<String, dynamic> _$$GetDoctorDetailsImplToJson(
        _$GetDoctorDetailsImpl instance) =>
    <String, dynamic>{
      'PRC_Number': instance.prcNumber,
      'City_Id': instance.cityId,
      'City_Name': instance.cityName,
      'Language_Name': instance.languageName,
      'Language_Id': instance.languageId,
      'Middle_Name': instance.middleName,
      'Last_Name': instance.lastName,
      'URL': instance.url,
      'Virtual': instance.virtual,
      'Service': instance.service,
      'Online': instance.online,
      'AccountName': instance.accountName,
      'BankName': instance.bankName,
      'AccountNo': instance.accountNo,
      'BranchName': instance.branchName,
      'IFSCCode': instance.ifscCode,
      'Hospital_id': instance.hospitalId,
      'Hospital_Name': instance.hospitalName,
      'Password': instance.password,
      'Lat': instance.lat,
      'DoctorCategory_id': instance.doctorCategoryId,
      'DoctorCategory_Name': instance.doctorCategoryName,
      'file': instance.file,
      'Long': instance.long,
      'Location_Name': instance.locationName,
      'Category': instance.category,
      'Doctor_id': instance.doctorId,
      'Doctor_Name': instance.doctorName,
      'QualificationName': instance.qualificationName,
      'Doctor_Qualification': instance.doctorQualification,
      'Location_id': instance.locationId,
      'SubCategory_id': instance.subCategoryId,
      'DoctorExperience_Years': instance.doctorExperienceYears,
      'Recommendations': instance.recommendations,
      'Doctor_Description': instance.doctorDescription,
      'Doctor_Image': instance.doctorImage,
      'Doctor_Age': instance.doctorAge,
      'Doctor_PhoneNumber': instance.doctorPhoneNumber,
      'SubCategory_Name': instance.subCategoryName,
      'Doctor_Address': instance.doctorAddress,
      'ClinicDoctorFee': instance.clinicDoctorFee,
      'Type_Flag': instance.typeFlag,
      'Days': instance.days,
      'sscategory_Name': instance.sscategoryName,
      'sscat_id': instance.sscatId,
      'Email_id': instance.emailId,
      'SubCat': instance.subCat,
      'Gender': instance.gender,
      'Status': instance.status,
      'Flag': instance.flag,
      'Doctor_Mobile_countrycode': instance.doctorMobileCountrycode,
      'Doctor_QualificationCode': instance.doctorQualificationCode,
      'Doctor_DOB': instance.doctorDob,
      'Doctor_List': instance.doctorList,
      'City_List': instance.cityList,
      'Langugage_List': instance.langList,
      'Doclist': instance.docList,
      'QualificationList': instance.qualificationList,
      'CategoryList': instance.categoryList,
    };
