// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'instant_doctor.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_InstantDoctor _$$_InstantDoctorFromJson(Map<String, dynamic> json) =>
    _$_InstantDoctor(
      RelationShipList: json['RelationShipList'] ?? '',
      BookCheck: json['BookCheck'] ?? '',
      Registrations: json['Registrations'] ?? '',
      Doctor_Qualification: json['Doctor_Qualification'] ?? '',
      Gender: json['Gender'] ?? '',
      Doctor_ExperienceYears: json['Doctor_ExperienceYears'] ?? '',
      Wallet_Amount: json['Wallet_Amount'] ?? '',
      Coupon_Amount: json['Coupon_Amount'] ?? '',
      Consultation_Amount: json['Consultation_Amount'] ?? '',
      Service_Charges: json['Service_Charges'] ?? '',
      Discount_Name: json['Discount_Name'] ?? '',
      Discount_Id: json['Discount_Id'] ?? '',
      Discount_Amount: json['Discount_Amount'] ?? '',
      Timing: json['Timing'] ?? '',
      Favorite: json['Favorite'] ?? '',
      PaymentGateway: json['PaymentGateway'] ?? '',
      Hospital_Name: json['Hospital_Name'] ?? '',
      Doctor_Name: json['Doctor_Name'] ?? '',
      eclinicVideo: json['eclinicVideo'] ?? '',
      Language_Name: json['Language_Name'] ?? '',
      city_name: json['city_name'] ?? '',
      Doctor_id: json['Doctor_id'] ?? '',
      Minutes: json['Minutes'] ?? '',
      CNT: json['CNT'] ?? '',
      Queue_id: json['Queue_id'] ?? '',
      QueueList: json['QueueList'] ?? '',
      Image: json['Image'] ?? '',
      DFSendList: json['DFSendList'] ?? '',
      Hospital_Banner_Image: json['Hospital_Banner_Image'] ?? '',
      Text_Color: json['Text_Color'] ?? '',
      Color_1: json['Color_1'] ?? '',
      Color_2: json['Color_2'] ?? '',
      ClinicFee: json['ClinicFee'] ?? '',
      Eclinic_Flag: json['Eclinic_Flag'] ?? '',
      Eclinic_Charges: json['Eclinic_Charges'] ?? null,
      Fee: json['Fee'] ?? null,
      Eclinic_Booking_Charges: json['Eclinic_Booking_Charges'] ?? '',
      Doctor_Designation: json['Doctor_Designation'] ?? '',
      Coupon_Flag: json['Coupon_Flag'] ?? '',
      Second_Image: json['Second_Image'] ?? '',
      Token_Number: json['Token_Number'] ?? '',
      Waiting_Time: json['Waiting_Time'] ?? '',
    );

Map<String, dynamic> _$$_InstantDoctorToJson(_$_InstantDoctor instance) =>
    <String, dynamic>{
      'RelationShipList': instance.RelationShipList,
      'BookCheck': instance.BookCheck,
      'Registrations': instance.Registrations,
      'Doctor_Qualification': instance.Doctor_Qualification,
      'Gender': instance.Gender,
      'Doctor_ExperienceYears': instance.Doctor_ExperienceYears,
      'Wallet_Amount': instance.Wallet_Amount,
      'Coupon_Amount': instance.Coupon_Amount,
      'Consultation_Amount': instance.Consultation_Amount,
      'Service_Charges': instance.Service_Charges,
      'Discount_Name': instance.Discount_Name,
      'Discount_Id': instance.Discount_Id,
      'Discount_Amount': instance.Discount_Amount,
      'Timing': instance.Timing,
      'Favorite': instance.Favorite,
      'PaymentGateway': instance.PaymentGateway,
      'Hospital_Name': instance.Hospital_Name,
      'Doctor_Name': instance.Doctor_Name,
      'eclinicVideo': instance.eclinicVideo,
      'Language_Name': instance.Language_Name,
      'city_name': instance.city_name,
      'Doctor_id': instance.Doctor_id,
      'Minutes': instance.Minutes,
      'CNT': instance.CNT,
      'Queue_id': instance.Queue_id,
      'QueueList': instance.QueueList,
      'Image': instance.Image,
      'DFSendList': instance.DFSendList,
      'Hospital_Banner_Image': instance.Hospital_Banner_Image,
      'Text_Color': instance.Text_Color,
      'Color_1': instance.Color_1,
      'Color_2': instance.Color_2,
      'ClinicFee': instance.ClinicFee,
      'Eclinic_Flag': instance.Eclinic_Flag,
      'Eclinic_Charges': instance.Eclinic_Charges,
      'Fee': instance.Fee,
      'Eclinic_Booking_Charges': instance.Eclinic_Booking_Charges,
      'Doctor_Designation': instance.Doctor_Designation,
      'Coupon_Flag': instance.Coupon_Flag,
      'Second_Image': instance.Second_Image,
      'Token_Number': instance.Token_Number,
      'Waiting_Time': instance.Waiting_Time,
    };
