// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'intake_object.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$IntakeObjectImpl _$$IntakeObjectImplFromJson(Map<String, dynamic> json) =>
    _$IntakeObjectImpl(
      Saturation: json['Saturation'] ?? null,
      Diastolic: json['Diastolic'] ?? null,
      Systolic: json['Systolic'] ?? null,
      Stools: json['Stools'] ?? null,
      Bath: json['Bath'] ?? null,
      Outdata_Quantity: json['Outdata_Quantity'] ?? null,
      Urine: json['Urine'] ?? null,
      Vomit: json['Vomit'] ?? null,
      Fesces: json['Fesces'] ?? null,
      id: json['id'] ?? null,
      date: json['date'] ?? null,
      time: json['time'] ?? null,
      particular: json['particular'] ?? null,
      fluids: json['fluids'] ?? null,
      oral: json['oral'] ?? null,
      noof_stool: json['noof_stool'] ?? null,
      noof_urine: json['noof_urine'] ?? null,
      admission_id: json['admission_id'] ?? null,
      patient_id: json['patient_id'] ?? null,
      doctor_id: json['doctor_id'] ?? null,
      prepared_by: json['prepared_by'] ?? null,
      insertdate: json['insertdate'] ?? null,
      prepared_name: json['prepared_name'] ?? null,
      focus: json['focus'] ?? null,
      notes: json['notes'] ?? null,
      pulse_rate: json['pulse_rate'] ?? null,
      bp: json['bp'] ?? null,
      temperature: json['temperature'] ?? null,
      respiration: json['respiration'] ?? null,
      height: json['height'] ?? null,
      weight: json['weight'] ?? null,
      Descriptionofintake: json['Descriptionofintake'] ?? null,
      Intake_Quantity: json['Intake_Quantity'] ?? null,
      Oral_Diet: json['Oral_Diet'] ?? null,
      Oral_Medication: json['Oral_Medication'] ?? null,
    );

Map<String, dynamic> _$$IntakeObjectImplToJson(_$IntakeObjectImpl instance) =>
    <String, dynamic>{
      'Saturation': instance.Saturation,
      'Diastolic': instance.Diastolic,
      'Systolic': instance.Systolic,
      'Stools': instance.Stools,
      'Bath': instance.Bath,
      'Outdata_Quantity': instance.Outdata_Quantity,
      'Urine': instance.Urine,
      'Vomit': instance.Vomit,
      'Fesces': instance.Fesces,
      'id': instance.id,
      'date': instance.date,
      'time': instance.time,
      'particular': instance.particular,
      'fluids': instance.fluids,
      'oral': instance.oral,
      'noof_stool': instance.noof_stool,
      'noof_urine': instance.noof_urine,
      'admission_id': instance.admission_id,
      'patient_id': instance.patient_id,
      'doctor_id': instance.doctor_id,
      'prepared_by': instance.prepared_by,
      'insertdate': instance.insertdate,
      'prepared_name': instance.prepared_name,
      'focus': instance.focus,
      'notes': instance.notes,
      'pulse_rate': instance.pulse_rate,
      'bp': instance.bp,
      'temperature': instance.temperature,
      'respiration': instance.respiration,
      'height': instance.height,
      'weight': instance.weight,
      'Descriptionofintake': instance.Descriptionofintake,
      'Intake_Quantity': instance.Intake_Quantity,
      'Oral_Diet': instance.Oral_Diet,
      'Oral_Medication': instance.Oral_Medication,
    };
