// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'medical_record.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$MedicalRecordImpl _$$MedicalRecordImplFromJson(Map<String, dynamic> json) =>
    _$MedicalRecordImpl(
      DeptName: json['DeptName'] ?? '',
      reApp_Date: json['reApp_Date'] ?? '',
      Revisit_Appointment_id: json['Revisit_Appointment_id'] ?? '',
      reApp_Time: json['reApp_Time'] ?? '',
      Doctor_Notes: json['Doctor_Notes'] ?? '',
      Hospital_id: json['Hospital_id'] ?? '',
      Timing: json['Timing'] ?? '',
      Hospital_PhoneNumber: json['Hospital_PhoneNumber'] ?? '',
      Allergie_id: json['Allergie_id'] ?? '',
      finding: json['finding'] ?? '',
      CountList: json['CountList'] ?? '',
      Allergie_Name: json['Allergie_Name'] ?? '',
      Doctor_id: json['Doctor_id'] ?? '',
      test_id: json['test_id'] ?? '',
      test_cost: json['test_cost'] ?? '',
      Doctor_Name: json['Doctor_Name'] ?? '',
      alter_flag: json['alter_flag'] ?? '',
      Doctor_Image: json['Doctor_Image'] ?? '',
      Doctor_Qualification: json['Doctor_Qualification'] ?? '',
      SubCategory_Name: json['SubCategory_Name'] ?? '',
      Type_Flag: json['Type_Flag'] ?? '',
      file_name: json['file_name'] ?? '',
      test_name: json['test_name'] ?? '',
      User_Name: json['User_Name'] ?? '',
      User_Image: json['User_Image'] ?? '',
      User_address: json['User_address'] ?? '',
      User_bloodgroup: json['User_bloodgroup'] ?? '',
      User_dob: json['User_dob'] ?? '',
      Emailid: json['Emailid'] ?? '',
      MobileNumber: json['MobileNumber'] ?? '',
      Location_Name: json['Location_Name'] ?? '',
      Hospital_Name: json['Hospital_Name'] ?? '',
      Hospital_Address: json['Hospital_Address'] ?? '',
      Clinic_id: json['Clinic_id'] ?? '',
      Clinic_Name: json['Clinic_Name'] ?? '',
      Clinic_Address: json['Clinic_Address'] ?? '',
      cancel_flag: json['cancel_flag'] ?? '',
      SubCategory_id: json['SubCategory_id'] ?? '',
      Location_id: json['Location_id'] ?? '',
      ClinicDoctorFee: json['ClinicDoctorFee'] ?? '',
      FromTime: json['FromTime'] ?? '',
      startSplit: json['startSplit'] ?? '',
      EndSplit: json['EndSplit'] ?? '',
      ToTime: json['ToTime'] ?? '',
      Day: json['Day'] ?? '',
      AboutClinic: json['AboutClinic'] ?? '',
      Clinic_Images: json['Clinic_Images'] ?? '',
      Appointment_Date: json['Appointment_Date'] ?? '',
      Appointment_id: json['Appointment_id'] ?? '',
      Appointment_Time: json['Appointment_Time'] ?? '',
      Confirm_Status: json['Confirm_Status'] ?? '',
      hospital_images: json['hospital_images'] ?? '',
      User_id: json['User_id'] ?? '',
      description: json['description'] ?? '',
      file: json['file'] ?? '',
      folder_date: json['folder_date'] ?? '',
      disease: json['disease'] ?? '',
      allergies: json['allergies'] ?? '',
      symptoms1: json['symptoms1'] ?? '',
      symptoms2: json['symptoms2'] ?? '',
      symptoms3: json['symptoms3'] ?? '',
      height: json['height'] ?? '',
      weight: json['weight'] ?? '',
      temp: json['temp'] ?? '',
      diabetes: json['diabetes'] ?? '',
      date: json['date'] ?? '',
      symptoms: json['symptoms'] ?? '',
      view_status: json['view_status'] ?? '',
      files: json['files'] ?? '',
      prescription: json['prescription'] ?? '',
      lab: json['lab'] ?? '',
      pat_list: json['pat_list'] ?? '',
      summary: json['summary'] ?? '',
      hos_list: json['hos_list'] ?? '',
      total: json['total'] ?? '',
      waiting: json['waiting'] ?? '',
      upcoming: json['upcoming'] ?? '',
      completed: json['completed'] ?? '',
      dosage: json['dosage'] ?? '',
      drug_name: json['drug_name'] ?? '',
      frequency: json['frequency'] ?? '',
      duration: json['duration'] ?? '',
      instruction: json['instruction'] ?? '',
      notes: json['notes'] ?? '',
      error: json['error'] ?? '',
      treatment_date: json['treatment_date'] ?? '',
      treatment_id: json['treatment_id'] ?? '',
      treatment_name: json['treatment_name'] ?? '',
      cost: json['cost'] ?? '',
      days: json['days'] ?? '',
      discount: json['discount'] ?? '',
      grant_total: json['grant_total'] ?? '',
      treatment: json['treatment'] ?? '',
      bill_date: json['bill_date'] ?? '',
      bill_id: json['bill_id'] ?? '',
      bill_name: json['bill_name'] ?? '',
      file_type: json['file_type'] ?? '',
      upload_date: json['upload_date'] ?? '',
      billing: json['billing'] ?? '',
      labtest_date: json['labtest_date'] ?? '',
      labtest_id: json['labtest_id'] ?? '',
      test_code: json['test_code'] ?? '',
      labtest_name: json['labtest_name'] ?? '',
      labtest: json['labtest'] ?? '',
      labname: json['labname'] ?? '',
      app_amount: json['app_amount'] ?? '',
      eclinic_amount: json['eclinic_amount'] ?? '',
      service_amount: json['service_amount'] ?? '',
      app_count: json['app_count'] ?? '',
      eclinic_count: json['eclinic_count'] ?? '',
      service_count: json['service_count'] ?? '',
      lab_id: json['lab_id'] ?? '',
      lab_name: json['lab_name'] ?? '',
      jan: json['jan'] ?? '',
      feb: json['feb'] ?? '',
      mar: json['mar'] ?? '',
      apr: json['apr'] ?? '',
      may: json['may'] ?? '',
      jun: json['jun'] ?? '',
      jul: json['jul'] ?? '',
      aug: json['aug'] ?? '',
      sep: json['sep'] ?? '',
      oct: json['oct'] ?? '',
      nov: json['nov'] ?? '',
      dec: json['dec'] ?? '',
      specialization: json['specialization'] ?? '',
      Lab_Result: json['Lab_Result'] ?? '',
      Payment_Flag: json['Payment_Flag'] ?? '',
      E_Flag: json['E_Flag'] ?? '',
      Test_Status_Flag: json['Test_Status_Flag'] ?? '',
      Follow_Up_Date: json['Follow_Up_Date'] ?? '',
      Follow_Up_Time: json['Follow_Up_Time'] ?? '',
      Follow_Up_Flag: json['Follow_Up_Flag'] ?? '',
      Sample_Flag: json['Sample_Flag'] ?? '',
      Sample_Date: json['Sample_Date'] ?? '',
      Result_Flag: json['Result_Flag'] ?? '',
      Result_Date: json['Result_Date'] ?? '',
      Result_Time: json['Result_Time'] ?? '',
      Expected_Date: json['Expected_Date'] ?? '',
      cancelalert_hour: json['cancelalert_hour'] ?? '',
      cancelalert_notes: json['cancelalert_notes'] ?? '',
      NightTime: json['NightTime'] ?? '',
      AfternoonTime: json['AfternoonTime'] ?? '',
      MorningTime: json['MorningTime'] ?? '',
      FoodInstr: json['FoodInstr'] ?? '',
      PresHalf_id: json['PresHalf_id'] ?? '',
      Test_Result_Property: json['Test_Result_Property'] ?? '',
      Approved_Status: json['Approved_Status'] ?? '',
      ReleasedStatus: json['ReleasedStatus'] ?? '',
      Key_Id: json['Key_Id'] ?? '',
      order_id: json['order_id'] ?? '',
      Confirm_Mail_Flag: json['Confirm_Mail_Flag'] ?? '',
      Vital_Flag: json['Vital_Flag'] ?? '',
      Token_Number: json['Token_Number'] ?? '',
      R_App: json['R_App'] ?? '',
      C_App: json['C_App'] ?? '',
      OT_RequestCount: json['OT_RequestCount'] ?? '',
      IP_app_count: json['IP_app_count'] ?? '',
      Emergrncy_app_count: json['Emergrncy_app_count'] ?? '',
      Missed: json['Missed'] ?? '',
      confirmed: json['confirmed'] ?? '',
      IP_waiting: json['IP_waiting'] ?? '',
      OT_Completed: json['OT_Completed'] ?? '',
      intakeObject: json['Intake_Object'] == null
          ? null
          : IntakeObject.fromJson(
              json['Intake_Object'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$MedicalRecordImplToJson(_$MedicalRecordImpl instance) =>
    <String, dynamic>{
      'DeptName': instance.DeptName,
      'reApp_Date': instance.reApp_Date,
      'Revisit_Appointment_id': instance.Revisit_Appointment_id,
      'reApp_Time': instance.reApp_Time,
      'Doctor_Notes': instance.Doctor_Notes,
      'Hospital_id': instance.Hospital_id,
      'Timing': instance.Timing,
      'Hospital_PhoneNumber': instance.Hospital_PhoneNumber,
      'Allergie_id': instance.Allergie_id,
      'finding': instance.finding,
      'CountList': instance.CountList,
      'Allergie_Name': instance.Allergie_Name,
      'Doctor_id': instance.Doctor_id,
      'test_id': instance.test_id,
      'test_cost': instance.test_cost,
      'Doctor_Name': instance.Doctor_Name,
      'alter_flag': instance.alter_flag,
      'Doctor_Image': instance.Doctor_Image,
      'Doctor_Qualification': instance.Doctor_Qualification,
      'SubCategory_Name': instance.SubCategory_Name,
      'Type_Flag': instance.Type_Flag,
      'file_name': instance.file_name,
      'test_name': instance.test_name,
      'User_Name': instance.User_Name,
      'User_Image': instance.User_Image,
      'User_address': instance.User_address,
      'User_bloodgroup': instance.User_bloodgroup,
      'User_dob': instance.User_dob,
      'Emailid': instance.Emailid,
      'MobileNumber': instance.MobileNumber,
      'Location_Name': instance.Location_Name,
      'Hospital_Name': instance.Hospital_Name,
      'Hospital_Address': instance.Hospital_Address,
      'Clinic_id': instance.Clinic_id,
      'Clinic_Name': instance.Clinic_Name,
      'Clinic_Address': instance.Clinic_Address,
      'cancel_flag': instance.cancel_flag,
      'SubCategory_id': instance.SubCategory_id,
      'Location_id': instance.Location_id,
      'ClinicDoctorFee': instance.ClinicDoctorFee,
      'FromTime': instance.FromTime,
      'startSplit': instance.startSplit,
      'EndSplit': instance.EndSplit,
      'ToTime': instance.ToTime,
      'Day': instance.Day,
      'AboutClinic': instance.AboutClinic,
      'Clinic_Images': instance.Clinic_Images,
      'Appointment_Date': instance.Appointment_Date,
      'Appointment_id': instance.Appointment_id,
      'Appointment_Time': instance.Appointment_Time,
      'Confirm_Status': instance.Confirm_Status,
      'hospital_images': instance.hospital_images,
      'User_id': instance.User_id,
      'description': instance.description,
      'file': instance.file,
      'folder_date': instance.folder_date,
      'disease': instance.disease,
      'allergies': instance.allergies,
      'symptoms1': instance.symptoms1,
      'symptoms2': instance.symptoms2,
      'symptoms3': instance.symptoms3,
      'height': instance.height,
      'weight': instance.weight,
      'temp': instance.temp,
      'diabetes': instance.diabetes,
      'date': instance.date,
      'symptoms': instance.symptoms,
      'view_status': instance.view_status,
      'files': instance.files,
      'prescription': instance.prescription,
      'lab': instance.lab,
      'pat_list': instance.pat_list,
      'summary': instance.summary,
      'hos_list': instance.hos_list,
      'total': instance.total,
      'waiting': instance.waiting,
      'upcoming': instance.upcoming,
      'completed': instance.completed,
      'dosage': instance.dosage,
      'drug_name': instance.drug_name,
      'frequency': instance.frequency,
      'duration': instance.duration,
      'instruction': instance.instruction,
      'notes': instance.notes,
      'error': instance.error,
      'treatment_date': instance.treatment_date,
      'treatment_id': instance.treatment_id,
      'treatment_name': instance.treatment_name,
      'cost': instance.cost,
      'days': instance.days,
      'discount': instance.discount,
      'grant_total': instance.grant_total,
      'treatment': instance.treatment,
      'bill_date': instance.bill_date,
      'bill_id': instance.bill_id,
      'bill_name': instance.bill_name,
      'file_type': instance.file_type,
      'upload_date': instance.upload_date,
      'billing': instance.billing,
      'labtest_date': instance.labtest_date,
      'labtest_id': instance.labtest_id,
      'test_code': instance.test_code,
      'labtest_name': instance.labtest_name,
      'labtest': instance.labtest,
      'labname': instance.labname,
      'app_amount': instance.app_amount,
      'eclinic_amount': instance.eclinic_amount,
      'service_amount': instance.service_amount,
      'app_count': instance.app_count,
      'eclinic_count': instance.eclinic_count,
      'service_count': instance.service_count,
      'lab_id': instance.lab_id,
      'lab_name': instance.lab_name,
      'jan': instance.jan,
      'feb': instance.feb,
      'mar': instance.mar,
      'apr': instance.apr,
      'may': instance.may,
      'jun': instance.jun,
      'jul': instance.jul,
      'aug': instance.aug,
      'sep': instance.sep,
      'oct': instance.oct,
      'nov': instance.nov,
      'dec': instance.dec,
      'specialization': instance.specialization,
      'Lab_Result': instance.Lab_Result,
      'Payment_Flag': instance.Payment_Flag,
      'E_Flag': instance.E_Flag,
      'Test_Status_Flag': instance.Test_Status_Flag,
      'Follow_Up_Date': instance.Follow_Up_Date,
      'Follow_Up_Time': instance.Follow_Up_Time,
      'Follow_Up_Flag': instance.Follow_Up_Flag,
      'Sample_Flag': instance.Sample_Flag,
      'Sample_Date': instance.Sample_Date,
      'Result_Flag': instance.Result_Flag,
      'Result_Date': instance.Result_Date,
      'Result_Time': instance.Result_Time,
      'Expected_Date': instance.Expected_Date,
      'cancelalert_hour': instance.cancelalert_hour,
      'cancelalert_notes': instance.cancelalert_notes,
      'NightTime': instance.NightTime,
      'AfternoonTime': instance.AfternoonTime,
      'MorningTime': instance.MorningTime,
      'FoodInstr': instance.FoodInstr,
      'PresHalf_id': instance.PresHalf_id,
      'Test_Result_Property': instance.Test_Result_Property,
      'Approved_Status': instance.Approved_Status,
      'ReleasedStatus': instance.ReleasedStatus,
      'Key_Id': instance.Key_Id,
      'order_id': instance.order_id,
      'Confirm_Mail_Flag': instance.Confirm_Mail_Flag,
      'Vital_Flag': instance.Vital_Flag,
      'Token_Number': instance.Token_Number,
      'R_App': instance.R_App,
      'C_App': instance.C_App,
      'OT_RequestCount': instance.OT_RequestCount,
      'IP_app_count': instance.IP_app_count,
      'Emergrncy_app_count': instance.Emergrncy_app_count,
      'Missed': instance.Missed,
      'confirmed': instance.confirmed,
      'IP_waiting': instance.IP_waiting,
      'OT_Completed': instance.OT_Completed,
      'Intake_Object': instance.intakeObject,
    };
