// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$UserImpl _$$UserImplFromJson(Map<String, dynamic> json) => _$UserImpl(
      id: json['Doctor_id'] ?? null,
      userId: json['User_id'] ?? null,
      bookCheck: json['BookCheck'] as String?,
      gender: (json['Gender'] as num?)?.toInt(),
      registration: json['Registrations'] as String?,
      pClainId: json['PClaim_id'] as num?,
      pDoctorName: json['PDoctor_Name'] as num?,
      pHospitalName: json['PHospital_Name'] as num?,
      pDoctorImage: json['PDoctor_Image'] as num?,
      pAppointmentSchedule: json['PAppointment_Schedule'] as num?,
      pConsulationFee: json['PConsultation_Fee'] as num?,
      pFlag: json['PFlag'] as String?,
      feedback: json['FeedBack'] as num?,
      subList: json['SubList'] as String?,
      eClinicFlag: json['eclinic_Flag'] as String?,
      cityListDisplay: json['CityListDisplay'] as String?,
      cityNameTmp: json['City_NameTmp'] as String?,
      cityName: json['City_Name'] as String?,
      cityId: json['City_id'] as num?,
      locationNameTemp: json['Location_Name_Temp'] as String?,
      urlString: json['URL_String'] as String?,
      specialization: json['Specialization'] as String?,
      fullName: json['Doctor_Name'] as String?,
      name: json['Name'] as String?,
      nameTemp: json['Doctor_Name_temp'] as String?,
      doctorQualification: json['Doctor_Qualification'] as String?,
      qualification: json['Qualification'] as String?,
      locationId: json['Location_id'] as num?,
      locationName: json['Location_name'] as String?,
      subCategoryId: json['SubCategory_id'] as num?,
      sscatId: json['sscat_id'] as num?,
      sscategoryName: json['sscategory_Name'] as String?,
      experience: json['DoctorExperience_Years'] as num?,
      recommendations: json['Recommendations'] as String?,
      description: json['Doctor_Description'] as String?,
      image: json['Doctor_Image'] as String?,
      age: (json['Doctor_Age'] as num?)?.toInt(),
      phone: json['Doctor_PhoneNumber'] as String?,
      subCategoryName: json['SubCategory_Name'] as String?,
      subCategoryNameTemp: json['SubCategory_Name_temp'] as String?,
      address: json['Doctor_Address'] as String?,
      type: json['type'] as String?,
      clinicDoctorFee: json['ClinicDoctorFee'] as num?,
      typeFlag: json['Type_Flag'] as String?,
      days: json['Days'] as String?,
      daysTotal: json['Dayslot'] as String?,
      clinicImages: json['Clinic_Images'] as String?,
      cImage: json['CImage'] as String?,
      fromTime: json['FromTime'] as String?,
      toTime: json['ToTime'] as String?,
      email: json['Doctor_Email'] as String?,
      emailId: json['EMail_Id'] as String?,
      password: json['Password'] as String?,
      hospitalList: json['Hospital_List'] as String?,
      subCatList: json['subcatlist'] as String?,
      locationNewList: json['LocationNewList'] as String?,
      betweenDistance: json['Between_Distance'] as num?,
      serviceId: json['service_id'] as num?,
      serviceName: json['service_name'] as String?,
      endorseList: json['endorse_list'] as String?,
      cancelFlag: json['cancel_flag'] as String?,
      clinicId: json['clinicid'] as num?,
      clinicName: json['clinicname'] as String?,
      clinicFee: json['clinicfee'] as num?,
      latitude: json['Latitude'] as String?,
      longitude: json['Longitude'] as String?,
      hospitalName: json['Hospital_Name'] as String?,
      hospitalNumber: json['Hospital_Number'] as String?,
      countryId: json['Country_Id'] as num?,
      clinicModel: json['Clinic_Model'] as String?,
      doctorUrlWithName: json['Doctor_Url_With_Name'] as String?,
      doctorUrlCity: json['Doctor_URL_City'] as String?,
      designation: json['Doctor_Designation'] as String?,
      phoneNumber: json['Phone_Number'] as String?,
      languageName: json['Language_Name'] as String?,
      whatsapp: json['Watsapp_Number'] as String?,
      patientid: json['Patient_Id'] ?? null,
      patientregistrationnumber: json['Patient_Registration_Number'] ?? null,
      firstname: json['First_Name'] ?? null,
      lastname: json['Last_Name'] ?? null,
      dob: json['DOB'] ?? null,
      patientage: json['Age'] ?? null,
      patientImage: json['Image'] ?? null,
      TTR: json['Time_in_Therapeutic_Ratio'] ?? null,
      TTRfrom: json['Traget_INR_From'] ?? null,
      TTRto: json['Traget_INR_To'] ?? null,
      date: json['Date'] ?? null,
      doctorActivationflag: json['Doctor_ActiveFlag'] ?? null,
      patientActivationflag: json['Patient_ActiveFlag'] ?? null,
      patientRegistrationlist: json['PatientRegistration_list'] ?? null,
      hospitalAdminId: json['Hospital_Admin_Id'] ?? null,
      hospitalId: json['Hospital_Id'] ?? null,
      hospitalEmailId: json['Email_Id'] ?? null,
      adminGender: json['AdminGender'] ?? null,
      adminAddress: json['Address'] ?? null,
      adminName: json['User_Firstname'] ?? null,
      adminNumber: json['Mobile_Number'] ?? null,
    );

Map<String, dynamic> _$$UserImplToJson(_$UserImpl instance) =>
    <String, dynamic>{
      'Doctor_id': instance.id,
      'User_id': instance.userId,
      'BookCheck': instance.bookCheck,
      'Gender': instance.gender,
      'Registrations': instance.registration,
      'PClaim_id': instance.pClainId,
      'PDoctor_Name': instance.pDoctorName,
      'PHospital_Name': instance.pHospitalName,
      'PDoctor_Image': instance.pDoctorImage,
      'PAppointment_Schedule': instance.pAppointmentSchedule,
      'PConsultation_Fee': instance.pConsulationFee,
      'PFlag': instance.pFlag,
      'FeedBack': instance.feedback,
      'SubList': instance.subList,
      'eclinic_Flag': instance.eClinicFlag,
      'CityListDisplay': instance.cityListDisplay,
      'City_NameTmp': instance.cityNameTmp,
      'City_Name': instance.cityName,
      'City_id': instance.cityId,
      'Location_Name_Temp': instance.locationNameTemp,
      'URL_String': instance.urlString,
      'Specialization': instance.specialization,
      'Doctor_Name': instance.fullName,
      'Name': instance.name,
      'Doctor_Name_temp': instance.nameTemp,
      'Doctor_Qualification': instance.doctorQualification,
      'Qualification': instance.qualification,
      'Location_id': instance.locationId,
      'Location_name': instance.locationName,
      'SubCategory_id': instance.subCategoryId,
      'sscat_id': instance.sscatId,
      'sscategory_Name': instance.sscategoryName,
      'DoctorExperience_Years': instance.experience,
      'Recommendations': instance.recommendations,
      'Doctor_Description': instance.description,
      'Doctor_Image': instance.image,
      'Doctor_Age': instance.age,
      'Doctor_PhoneNumber': instance.phone,
      'SubCategory_Name': instance.subCategoryName,
      'SubCategory_Name_temp': instance.subCategoryNameTemp,
      'Doctor_Address': instance.address,
      'type': instance.type,
      'ClinicDoctorFee': instance.clinicDoctorFee,
      'Type_Flag': instance.typeFlag,
      'Days': instance.days,
      'Dayslot': instance.daysTotal,
      'Clinic_Images': instance.clinicImages,
      'CImage': instance.cImage,
      'FromTime': instance.fromTime,
      'ToTime': instance.toTime,
      'Doctor_Email': instance.email,
      'EMail_Id': instance.emailId,
      'Password': instance.password,
      'Hospital_List': instance.hospitalList,
      'subcatlist': instance.subCatList,
      'LocationNewList': instance.locationNewList,
      'Between_Distance': instance.betweenDistance,
      'service_id': instance.serviceId,
      'service_name': instance.serviceName,
      'endorse_list': instance.endorseList,
      'cancel_flag': instance.cancelFlag,
      'clinicid': instance.clinicId,
      'clinicname': instance.clinicName,
      'clinicfee': instance.clinicFee,
      'Latitude': instance.latitude,
      'Longitude': instance.longitude,
      'Hospital_Name': instance.hospitalName,
      'Hospital_Number': instance.hospitalNumber,
      'Country_Id': instance.countryId,
      'Clinic_Model': instance.clinicModel,
      'Doctor_Url_With_Name': instance.doctorUrlWithName,
      'Doctor_URL_City': instance.doctorUrlCity,
      'Doctor_Designation': instance.designation,
      'Phone_Number': instance.phoneNumber,
      'Language_Name': instance.languageName,
      'Watsapp_Number': instance.whatsapp,
      'Patient_Id': instance.patientid,
      'Patient_Registration_Number': instance.patientregistrationnumber,
      'First_Name': instance.firstname,
      'Last_Name': instance.lastname,
      'DOB': instance.dob,
      'Age': instance.patientage,
      'Image': instance.patientImage,
      'Time_in_Therapeutic_Ratio': instance.TTR,
      'Traget_INR_From': instance.TTRfrom,
      'Traget_INR_To': instance.TTRto,
      'Date': instance.date,
      'Doctor_ActiveFlag': instance.doctorActivationflag,
      'Patient_ActiveFlag': instance.patientActivationflag,
      'PatientRegistration_list': instance.patientRegistrationlist,
      'Hospital_Admin_Id': instance.hospitalAdminId,
      'Hospital_Id': instance.hospitalId,
      'Email_Id': instance.hospitalEmailId,
      'AdminGender': instance.adminGender,
      'Address': instance.adminAddress,
      'User_Firstname': instance.adminName,
      'Mobile_Number': instance.adminNumber,
    };
