import 'package:freezed_annotation/freezed_annotation.dart';

part 'waiting_room_details.freezed.dart';
part 'waiting_room_details.g.dart';

@freezed
class WaitingRoomDetails with _$WaitingRoomDetails {
  const factory WaitingRoomDetails({

   required dynamic deptName,
    required dynamic doctorNotes,
    required int hospitalId,
    required dynamic timing,
    required dynamic hospitalPhoneNumber,
    required int allergieId,
    required dynamic finding,
    required dynamic countList,
    required dynamic allergieName,
    required int doctorId,
    required int testId,
    required int testCost,
    required dynamic doctorName,
    required dynamic alterFlag,
    required dynamic doctorImage,
    required dynamic doctorQualification,
    required dynamic subCategoryName,
    required dynamic typeFlag,
    required dynamic fileName,
    required dynamic testName,
    required dynamic userName,
    required dynamic userImage,
    required dynamic userAddress,
    required dynamic userBloodgroup,
    required dynamic userDob,
    required dynamic emailid,
    required dynamic mobileNumber,
    required dynamic locationName,
    required dynamic hospitalName,
    required dynamic hospitalAddress,
    required int clinicId,
    required dynamic clinicName,
    required dynamic clinicAddress,
    required dynamic cancelFlag,
    required int subCategoryId,
    required int locationId,
    required int clinicDoctorFee,
    required dynamic fromTime,
    required int startSplit,
    required int endSplit,
    required dynamic toTime,
    required dynamic day,
    required dynamic aboutClinic,
    required dynamic clinicImages,
    required dynamic appointmentDate,
    required int appointmentId,
    required dynamic appointmentTime,
    required dynamic confirmStatus,
    required dynamic hospitalImages,
    required int userId,
    required dynamic description,
    required dynamic file,
    required dynamic folderDate,
    required dynamic disease,
    required dynamic allergies,
    required dynamic symptoms1,
    required dynamic symptoms2,
    required dynamic symptoms3,
    required dynamic height,
    required dynamic weight,
    required dynamic temp,
    required dynamic diabetes,
    required dynamic date,
    required dynamic symptoms,
    required dynamic viewStatus,
    required dynamic files,
    required dynamic prescription,
    required dynamic lab,
    required dynamic patList,
    required dynamic summary,
    required dynamic hosList,
    required dynamic total,
    required dynamic waiting,
    required dynamic upcoming,
    required dynamic completed,
    required int dosage,
    required dynamic drugName,
    required dynamic frequency,
    required int duration,
    required dynamic instruction,
    required  dynamic notes,
    required  dynamic error,
    required dynamic treatmentDate,
    required int treatmentId,
    required dynamic treatmentName,
    required dynamic cost,
    required dynamic days,
    required dynamic discount,
    required dynamic grantTotal,
    required dynamic treatment,
    required dynamic billDate,
    required int billId,
    required dynamic billName,
    required dynamic fileType,
    required dynamic uploadDate,
    required dynamic billing,
    required dynamic labtestDate,
    required int labtestId,
    required dynamic testCode,
    required dynamic labtestName,
    required dynamic labtest,
    required dynamic labname,
    required dynamic appAmount,
    required dynamic eclinicAmount,
    required dynamic serviceAmount,
    required dynamic appCount,
    required dynamic eclinicCount,
    required dynamic serviceCount,
    required int labId,
    required dynamic labName,
    required dynamic jan,
    required dynamic feb,
    required dynamic mar,
    required dynamic apr,
    required dynamic may,
    required dynamic jun,
    required dynamic jul,
    required dynamic aug,
    required dynamic sep,
    required dynamic oct,
    required dynamic nov,
    required dynamic dec,
    required dynamic specialization,
    required dynamic labResult,
    required  dynamic paymentFlag,
    required dynamic eFlag,
    required dynamic testStatusFlag,
    required  dynamic followUpDate,
    required dynamic followUpTime,
    required dynamic followUpFlag,
    required dynamic sampleFlag,
    required dynamic sampleDate,
    required dynamic resultFlag,
    required dynamic resultDate,
    required dynamic resultTime,
    required dynamic expectedDate,
    required int cancelalertHour,
    required dynamic cancelalertNotes,
    required dynamic nightTime,
    required dynamic afternoonTime,
    required dynamic morningTime,
    required dynamic foodInstr,
    required dynamic presHalfId,
    required dynamic testResultProperty,
    required dynamic approvedStatus,
    required dynamic releasedStatus,
    required dynamic intakeObject,
    required dynamic keyId,
    required dynamic orderId,
    required dynamic confirmMailFlag,
    required dynamic vitalFlag,
    required dynamic tokenNumber,
    required int rApp,
    required int cApp,
    required dynamic oTRequestCount,
    required dynamic iPAppCount,
    required dynamic emergrncyAppCount,
    required dynamic missed,
    required dynamic confirmed,
    required dynamic iPWaiting,
    required dynamic oTCompleted,


  }) = _WaitingRoomDetails;
  static const fromJsonFactory = _$WaitingRoomDetailsFromJson;
  factory WaitingRoomDetails.fromJson(Map<String, dynamic> json) =>
      _$WaitingRoomDetailsFromJson(json);
}








